// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/marcellodesales/blackduck-mcp-server/internal/infra/blackduck"
	"github.com/marcellodesales/blackduck-mcp-server/internal/interfaces/httpserver"
	"github.com/marcellodesales/blackduck-mcp-server/internal/interfaces/mcp"
	"github.com/marcellodesales/blackduck-mcp-server/internal/platform/app"
	"github.com/marcellodesales/blackduck-mcp-server/internal/platform/config"
	"github.com/marcellodesales/blackduck-mcp-server/internal/platform/logging"
	"github.com/marcellodesales/blackduck-mcp-server/internal/platform/privateca"
	"github.com/marcellodesales/blackduck-mcp-server/internal/platform/wiring"
	"log/slog"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	logger, err := logging.New()
	if err != nil {
		return nil, err
	}
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	sealer, err := wiring.ProvideSealer(configConfig)
	if err != nil {
		return nil, err
	}
	service := wiring.ProvideAuthService(sealer)
	client, err := wiring.ProvideHTTPClient(configConfig)
	if err != nil {
		return nil, err
	}
	blackduckClient, err := blackduck.ProvideClient(configConfig, client)
	if err != nil {
		return nil, err
	}
	handler, err := mcpserver.NewHandler(configConfig, logger, service, blackduckClient)
	if err != nil {
		return nil, err
	}
	router := httpserver.NewRouter(configConfig, logger, handler, service, blackduckClient)
	httpHandler := httpserver.ProvideHandler(router)
	server := httpserver.NewServer(configConfig, httpHandler)
	bootstrapper := wiring.ProvidePrivateCABootstrapper(configConfig, logger)
	appApp := newApp(logger, server, bootstrapper)
	return appApp, nil
}

// wire.go:

func newApp(logger *slog.Logger, srv *http.Server, privateCABootstrapper *privateca.Bootstrapper) *app.App {
	return &app.App{
		Logger:                logger,
		HTTPServer:            srv,
		ShutdownTimeout:       10 * time.Second,
		PrivateCABootstrapper: privateCABootstrapper,
	}
}
